### ISSUE TITLE
UiPath Workflow

### ISSUE THREAD

**Issue by HeeruAhuja** [UiPath/AmazonConnect#2]
Hi, 
Could you please explain what the UiPath workflow would contain exactly? Also, by when will this project be done? I know you said June 2020 but I just want to confirm. I'm new to github so don't exactly know if this is the right place to ask. My apologies if it isin't.
Thanks.

**Comment by justmarks** [comment]
Happy to help here.  For the inbound demo, the workflow would contain take inputs from the contact flow (i.e. caller's phone number) and then do whatever you want to query the back end for information to present to the user.  In the demo, I had a dummy process that just outputs static text but you can imagine the process hitting mainframes, etc. to pass the phone number and get the actual billing data.

We're VERY close to having an updated version that leverages an Amazon CFT to deploy the E2E. The new version also has node versions of the lambdas.  We should update the repo with this by next week.

**Comment by justmarks** [comment]
The latest update includes the Node.js version of lambdas and the CFT for deployment
